### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by Inkrementator**
I'm mostly just putting this here in case you have some stylistic preferences so these can be sorted out before I do more.
I haven't set up the documentation builder yet so it's possible that it will look terrible once rendered.

TODO
* Demonstration Unit tests that show up in the docs (can I put these inside a struct?)
* serialize.d
* Example program in `examples/` that utilizes the serialize.d api

### CODE REVIEW

**Comment by schveiguy** [comment]
It is true my comments are inconsistent, but if we are going to use ddocs, it should be consistent (always /** or always ///)

I prefer the /** format.

Thanks. This project really needs some love...

**Comment by Inkrementator** [comment]
Some thoughts:

* make serializeImpl private so it doesn't clutter the docs
* serialize l. 380: `assert(false, "invalid hex number detected! " ~ window);`: Does assert(false, ...) get dropped in release mode by the compiler or is bare assert(false) the exception to this behaviour? Maybe enforce is more safe here

I still have to figure out how to best document toJSON and fromJSON. I remember especially struggling with fromJSON and knowing until where exactly I had to consume the input so the rest of the document continues to work as expected. 

One idea would be to write a test-case template mixin that takes in the object, wraps it in an array/ another struct and test a roundtrip.

**Comment by Inkrementator** [comment]
>One idea would be to write a test-case template mixin that takes in the object, wraps it in an array/ another struct and test a roundtrip.

On second thought, this sounds too convoluted (and very easy for the user to do for himself), forget that.

**Comment by schveiguy** [comment]
> * make serializeImpl private so it doesn't clutter the docs

Yeah, probably could do that.

**Comment by schveiguy** [comment]
> * Does assert(false, ...) get dropped in release mode by the compiler or is bare assert(false) the exception to this behaviour?

assert(false) always is included. In release mode, it turns into an abort (with no message).

The assert is correct in this case, because a `Hex` token type should be produced by the tokenizer only if the hex number is valid. In other words, if we got here, it's because there is a bug in the parser code.

**Comment by schveiguy** [comment]
> I still have to figure out how to best document toJSON and fromJSON.

OK, yeah this is a pretty rough edge of this library.

> I remember especially struggling with fromJSON and knowing until where exactly I had to consume the input so the rest of the document continues to work as expected.

Agreed, it probably would be nice to have a better interface for this.

**Comment by schveiguy** [comment]
I'll merge this now, lots of great work here, and more unittests!

**Comment by Inkrementator** [comment]
Hi, I didn't saw your edit in the mail and thus never bothered to check here again. Tbh I think the WIP was an error, but I've added some other things now that I noticed this PR.

**Comment by schveiguy** [comment]
Just FYI, super busy right now, but I will get back to this. I also forgot about it...

**Pull request merged**
